/*
 * Copyright (c) 2026 sameerasw.com
 * License: MIT License
 *
 * Feature Module: Domain Layer Models & Registries
 * File: AutomationSuggestion.kt
 * Description: Domain model and business logic entry for AutomationSuggestion.kt.
 */

package com.sameerasw.essentials.domain.genai

import androidx.annotation.Keep
import com.google.mlkit.genai.schema.annotations.Generable
import com.google.mlkit.genai.schema.annotations.Guide

@Keep
@Generable("Structured output representing an automation suggestion generated by Gemini Nano")
data class AutomationSuggestion(
    @Guide(
        description = "Type of automation: TRIGGER, STATE, or APP",
        enumValues = ["TRIGGER", "STATE", "APP"]
    )
    val type: String = "TRIGGER",

    @Guide(description = "Human-readable suggested title for the automation")
    val title: String = "",

    @Guide(
        description = "Trigger type if automation is TRIGGER type",
        enumValues = [
            "ScreenOff",
            "ScreenOn",
            "DeviceUnlock",
            "ChargerConnected",
            "ChargerDisconnected",
            "PowerSavingOn",
            "PowerSavingOff",
            "Schedule",
            "BluetoothConnected",
            "BluetoothDisconnected",
            "WifiConnected",
            "WifiDisconnected"
        ]
    )
    val triggerType: String? = null,

    @Guide(
        description = "State type if automation is STATE type",
        enumValues = ["Charging", "ScreenOn", "PowerSaving", "TimePeriod"]
    )
    val stateType: String? = null,

    @Guide(
        description = "List of action names to execute",
        minItems = 1,
        maxItems = 5
    )
    val actionTypes: List<String> = emptyList(),

    @Guide(description = "Brief human-readable summary of what this automation will do")
    val explanation: String = "",

    // Detailed Trigger / State configurations
    @Guide(description = "Hour for Schedule trigger or startHour for TimePeriod state (0-23)")
    val hour: Int? = null,

    @Guide(description = "Minute for Schedule trigger or startMinute for TimePeriod state (0-59)")
    val minute: Int? = null,

    @Guide(description = "End hour for TimePeriod state (0-23)")
    val endHour: Int? = null,

    @Guide(description = "End minute for TimePeriod state (0-59)")
    val endMinute: Int? = null,

    @Guide(description = "List of package names for APP type automations or targeted app actions")
    val selectedApps: List<String> = emptyList(),

    // Detailed Action configurations
    @Guide(description = "Sound mode setting for SoundMode action: SOUND, VIBRATE, or SILENT")
    val soundMode: String? = null,

    @Guide(description = "FreezeTag action mode: Freeze or Unfreeze")
    val freezeTagMode: String? = null,

    @Guide(description = "List of target AppTag IDs or Tag names for FreezeTag action")
    val freezeTagIds: List<String> = emptyList(),

    @Guide(description = "Lock screen clock style for SometimesEssentials action: DEFAULT, METRO, EXPRESSIVE, PRIDE, MONOSPACE, BUBBLE")
    val lockScreenClockStyle: String? = null,

    @Guide(description = "Always-on display mode for SometimesEssentials action: Off, Dynamic, On")
    val alwaysOnDisplayMode: String? = null,

    @Guide(description = "Essentials on display mode for SometimesEssentials action: Off, On, Docked")
    val essentialsOnDisplayMode: String? = null,

    @Guide(description = "Whether to enable flashlight pulse in SometimesEssentials action")
    val flashlightPulseEnabled: Boolean? = null,

    @Guide(description = "Whether to enable notification lighting in SometimesEssentials action")
    val notificationLightingEnabled: Boolean? = null,

    @Guide(description = "Whether to enable Smart Pixels in SometimesEssentials action")
    val smartPixelsEnabled: Boolean? = null,

    @Guide(description = "Dim wallpaper amount (0.0 to 1.0) for DimWallpaper action")
    val dimWallpaperAmount: Float? = null,

    @Guide(description = "Select keyboard from the list to switch")
    val keyboard: String? = null,
)
